export enum EventStatusType {
  SCHEDULED = 'SCHEDULED',
  STARTED = 'STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  POSTPONED = 'POSTPONED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED'
}
